services:
  database:
    build:
      context: ${ROOT_DIR}/docker/pgsql
      dockerfile: Dockerfile
    platform: linux/amd64
    image: literp_pgsql
    container_name: literp_pgsql
    restart: always
    networks:
      - project_network
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${ROOT_DIR}/docker/pgsql/data/00-init.sql:/init-data/00-init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
networks:
  project_network:
    name: ${DOCKER_NETWORK}
    external: true